// GENERATED by tools/gen-data.js from the original Sinclair 48K ROM.
// Do not edit by hand - re-run the generator instead.
export const FONT_BASE64 = "AAAAAAAAAAAAEBAQEAAQAAAkJAAAAAAAACR+JCR+JAAACD4oPgo+CABiZAgQJkYAABAoECpEOgAACBAAAAAAAAAECAgICAQAACAQEBAQIAAAABQIPggUAAAACAg+CAgAAAAAAAAICBAAAAAAPgAAAAAAAAAAGBgAAAACBAgQIAAAPEZKUmI8AAAYKAgICD4AADxCAjxAfgAAPEIMAkI8AAAIGChIfggAAH5AfAJCPAAAPEB8QkI8AAB+AgQIEBAAADxCPEJCPAAAPEJCPgI8AAAAABAAABAAAAAQAAAQECAAAAQIEAgEAAAAAD4APgAAAAAQCAQIEAAAPEIECAAIAAA8SlZeQDwAADxCQn5CQgAAfEJ8QkJ8AAA8QkBAQjwAAHhEQkJEeAAAfkB8QEB+AAB+QHxAQEAAADxCQE5CPAAAQkJ+QkJCAAA+CAgICD4AAAICAkJCPAAAREhwSERCAABAQEBAQH4AAEJmWkJCQgAAQmJSSkZCAAA8QkJCQjwAAHxCQnxAQAAAPEJCUko8AAB8QkJ8REIAADxAPAJCPAAA/hAQEBAQAABCQkJCQjwAAEJCQkIkGAAAQkJCQlokAABCJBgYJEIAAIJEKBAQEAAAfgQIECB+AAAOCAgICA4AAABAIBAIBAAAcBAQEBBwAAAQOFQQEBAAAAAAAAAAAP8AHCJ4ICB+AAAAOAQ8RDwAACAgPCIiPAAAABwgICAcAAAEBDxERDwAAAA4RHhAPAAADBAYEBAQAAAAPEREPAQ4AEBAeERERAAAEAAwEBA4AAAEAAQEBCQYACAoMDAoJAAAEBAQEBAMAAAAaFRUVFQAAAB4RERERAAAADhEREQ4AAAAeEREeEBAAAA8REQ8BAYAABwgICAgAAAAOEA4BHgAABA4EBAQDAAAAEREREQ4AAAAREQoKBAAAABEVFRUKAAAAEQoEChEAAAAREREPAQ4AAB8CBAgfAAADggwCAgOAAAICAgICAgAAHAQDBAQcAAAFCgAAAAAADxCmaGhmUI8";
export const TOKENS = {"164":"?","165":"RND","166":"INKEY$","167":"PI","168":"FN","169":"POINT","170":"SCREEN$","171":"ATTR","172":"AT","173":"TAB","174":"VAL$","175":"CODE","176":"VAL","177":"LEN","178":"SIN","179":"COS","180":"TAN","181":"ASN","182":"ACS","183":"ATN","184":"LN","185":"EXP","186":"INT","187":"SQR","188":"SGN","189":"ABS","190":"PEEK","191":"IN","192":"USR","193":"STR$","194":"CHR$","195":"NOT","196":"BIN","197":"OR","198":"AND","199":"<=","200":">=","201":"<>","202":"LINE","203":"THEN","204":"TO","205":"STEP","206":"DEF FN","207":"CAT","208":"FORMAT","209":"MOVE","210":"ERASE","211":"OPEN #","212":"CLOSE #","213":"MERGE","214":"VERIFY","215":"BEEP","216":"CIRCLE","217":"INK","218":"PAPER","219":"FLASH","220":"BRIGHT","221":"INVERSE","222":"OVER","223":"OUT","224":"LPRINT","225":"LLIST","226":"STOP","227":"READ","228":"DATA","229":"RESTORE","230":"NEW","231":"BORDER","232":"CONTINUE","233":"DIM","234":"REM","235":"FOR","236":"GO TO","237":"GO SUB","238":"INPUT","239":"LOAD","240":"LIST","241":"LET","242":"PAUSE","243":"NEXT","244":"POKE","245":"PRINT","246":"PLOT","247":"RUN","248":"SAVE","249":"RANDOMIZE","250":"IF","251":"CLS","252":"DRAW","253":"CLEAR","254":"RETURN","255":"COPY"};
export const KEYS = [
 {
  "id": "1",
  "matrix": [
   3,
   0
  ],
  "main": "1",
  "symbol": "!",
  "above": "EDIT",
  "below": "DEF FN",
  "colour": 1
 },
 {
  "id": "2",
  "matrix": [
   3,
   1
  ],
  "main": "2",
  "symbol": "@",
  "above": "CAPS LOCK",
  "below": "FN",
  "colour": 2
 },
 {
  "id": "3",
  "matrix": [
   3,
   2
  ],
  "main": "3",
  "symbol": "#",
  "above": "TRUE VIDEO",
  "below": "LINE",
  "colour": 3
 },
 {
  "id": "4",
  "matrix": [
   3,
   3
  ],
  "main": "4",
  "symbol": "$",
  "above": "INV.VIDEO",
  "below": "OPEN #",
  "colour": 4
 },
 {
  "id": "5",
  "matrix": [
   3,
   4
  ],
  "main": "5",
  "symbol": "%",
  "above": "←",
  "below": "CLOSE #",
  "colour": 5
 },
 {
  "id": "6",
  "matrix": [
   4,
   4
  ],
  "main": "6",
  "symbol": "&",
  "above": "↓",
  "below": "MOVE",
  "colour": 6
 },
 {
  "id": "7",
  "matrix": [
   4,
   3
  ],
  "main": "7",
  "symbol": "'",
  "above": "↑",
  "below": "ERASE",
  "colour": 7
 },
 {
  "id": "8",
  "matrix": [
   4,
   2
  ],
  "main": "8",
  "symbol": "(",
  "above": "→",
  "below": "POINT"
 },
 {
  "id": "9",
  "matrix": [
   4,
   1
  ],
  "main": "9",
  "symbol": ")",
  "above": "GRAPHICS",
  "below": "CAT"
 },
 {
  "id": "0",
  "matrix": [
   4,
   0
  ],
  "main": "0",
  "symbol": "_",
  "above": "DELETE",
  "below": "FORMAT",
  "colour": 0
 },
 {
  "id": "Q",
  "matrix": [
   2,
   0
  ],
  "main": "Q",
  "keyword": "PLOT",
  "symbol": "<=",
  "above": "SIN",
  "below": "ASN"
 },
 {
  "id": "W",
  "matrix": [
   2,
   1
  ],
  "main": "W",
  "keyword": "DRAW",
  "symbol": "<>",
  "above": "COS",
  "below": "ACS"
 },
 {
  "id": "E",
  "matrix": [
   2,
   2
  ],
  "main": "E",
  "keyword": "REM",
  "symbol": ">=",
  "above": "TAN",
  "below": "ATN"
 },
 {
  "id": "R",
  "matrix": [
   2,
   3
  ],
  "main": "R",
  "keyword": "RUN",
  "symbol": "<",
  "above": "INT",
  "below": "VERIFY"
 },
 {
  "id": "T",
  "matrix": [
   2,
   4
  ],
  "main": "T",
  "keyword": "RANDOMIZE",
  "symbol": ">",
  "above": "RND",
  "below": "MERGE"
 },
 {
  "id": "Y",
  "matrix": [
   5,
   4
  ],
  "main": "Y",
  "keyword": "RETURN",
  "symbol": "AND",
  "above": "STR$",
  "below": "["
 },
 {
  "id": "U",
  "matrix": [
   5,
   3
  ],
  "main": "U",
  "keyword": "IF",
  "symbol": "OR",
  "above": "CHR$",
  "below": "]"
 },
 {
  "id": "I",
  "matrix": [
   5,
   2
  ],
  "main": "I",
  "keyword": "INPUT",
  "symbol": "AT",
  "above": "CODE",
  "below": "IN"
 },
 {
  "id": "O",
  "matrix": [
   5,
   1
  ],
  "main": "O",
  "keyword": "POKE",
  "symbol": ";",
  "above": "PEEK",
  "below": "OUT"
 },
 {
  "id": "P",
  "matrix": [
   5,
   0
  ],
  "main": "P",
  "keyword": "PRINT",
  "symbol": "\"",
  "above": "TAB",
  "below": "©"
 },
 {
  "id": "A",
  "matrix": [
   1,
   0
  ],
  "main": "A",
  "keyword": "NEW",
  "symbol": "STOP",
  "above": "READ",
  "below": "~"
 },
 {
  "id": "S",
  "matrix": [
   1,
   1
  ],
  "main": "S",
  "keyword": "SAVE",
  "symbol": "NOT",
  "above": "RESTORE",
  "below": "|"
 },
 {
  "id": "D",
  "matrix": [
   1,
   2
  ],
  "main": "D",
  "keyword": "DIM",
  "symbol": "STEP",
  "above": "DATA",
  "below": "\\"
 },
 {
  "id": "F",
  "matrix": [
   1,
   3
  ],
  "main": "F",
  "keyword": "FOR",
  "symbol": "TO",
  "above": "SGN",
  "below": "{"
 },
 {
  "id": "G",
  "matrix": [
   1,
   4
  ],
  "main": "G",
  "keyword": "GO TO",
  "symbol": "THEN",
  "above": "ABS",
  "below": "}"
 },
 {
  "id": "H",
  "matrix": [
   6,
   4
  ],
  "main": "H",
  "keyword": "GO SUB",
  "symbol": "^",
  "above": "SQR",
  "below": "CIRCLE"
 },
 {
  "id": "J",
  "matrix": [
   6,
   3
  ],
  "main": "J",
  "keyword": "LOAD",
  "symbol": "-",
  "above": "VAL",
  "below": "VAL$"
 },
 {
  "id": "K",
  "matrix": [
   6,
   2
  ],
  "main": "K",
  "keyword": "LIST",
  "symbol": "+",
  "above": "LEN",
  "below": "SCREEN$"
 },
 {
  "id": "L",
  "matrix": [
   6,
   1
  ],
  "main": "L",
  "keyword": "LET",
  "symbol": "=",
  "above": "USR",
  "below": "ATTR"
 },
 {
  "id": "ENTER",
  "matrix": [
   6,
   0
  ],
  "main": "ENTER",
  "special": "ENTER"
 },
 {
  "id": "CS",
  "matrix": [
   0,
   0
  ],
  "main": "CAPS SHIFT",
  "special": "CS"
 },
 {
  "id": "Z",
  "matrix": [
   0,
   1
  ],
  "main": "Z",
  "keyword": "COPY",
  "symbol": ":",
  "above": "LN",
  "below": "BEEP"
 },
 {
  "id": "X",
  "matrix": [
   0,
   2
  ],
  "main": "X",
  "keyword": "CLEAR",
  "symbol": "£",
  "above": "EXP",
  "below": "INK"
 },
 {
  "id": "C",
  "matrix": [
   0,
   3
  ],
  "main": "C",
  "keyword": "CONTINUE",
  "symbol": "?",
  "above": "LPRINT",
  "below": "PAPER"
 },
 {
  "id": "V",
  "matrix": [
   0,
   4
  ],
  "main": "V",
  "keyword": "CLS",
  "symbol": "/",
  "above": "LLIST",
  "below": "FLASH"
 },
 {
  "id": "B",
  "matrix": [
   7,
   4
  ],
  "main": "B",
  "keyword": "BORDER",
  "symbol": "*",
  "above": "BIN",
  "below": "BRIGHT"
 },
 {
  "id": "N",
  "matrix": [
   7,
   3
  ],
  "main": "N",
  "keyword": "NEXT",
  "symbol": ",",
  "above": "INKEY$",
  "below": "OVER"
 },
 {
  "id": "M",
  "matrix": [
   7,
   2
  ],
  "main": "M",
  "keyword": "PAUSE",
  "symbol": ".",
  "above": "PI",
  "below": "INVERSE"
 },
 {
  "id": "SS",
  "matrix": [
   7,
   1
  ],
  "main": "SYMBOL SHIFT",
  "special": "SS"
 },
 {
  "id": "SPACE",
  "matrix": [
   7,
   0
  ],
  "main": "SPACE",
  "special": "SPACE",
  "above": "BREAK"
 }
];
