// Generates js/rom-data.js from the original 48K ROM.
// Everything here is DERIVED FROM THE ROM, not typed from memory.
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const rom = fs.readFileSync(path.join(ROOT, 'roms', '48.rom'));

if (rom.length !== 16384) throw new Error('ROM must be 16384 bytes, got ' + rom.length);

// ---- BASIC token names ($0095, last char of each entry has bit 7 set) ----
// The table opens with a dummy "?" entry, so the first real token (RND) is 165.
const tokens = {};
{
  let p = 0x0095, code = 164, cur = '';
  while (code <= 255) {
    const b = rom[p++];
    cur += String.fromCharCode(b & 0x7f);
    if (b & 0x80) { tokens[code] = cur; cur = ''; code++; }
  }
}
const tok = c => tokens[c];

// ---- Key tables ----
const KEY_MAIN   = 0x0205; // 39 entries, keyboard scan order
const KEY_EXT    = 0x022C; // 26, extended mode, letters A..Z
const KEY_EXTSS  = 0x0246; // 26, extended mode + SYMBOL SHIFT, letters A..Z
const KEY_CTRL   = 0x0260; // 10, CAPS SHIFT + digits 0..9
const KEY_SS     = 0x026A; // 26, SYMBOL SHIFT, letters A..Z
const KEY_EXTDIG = 0x0284; // 10, extended mode + SYMBOL SHIFT, digits 0..9

const byteAt = (base, i) => rom[base + i];
const letterIdx = ch => ch.charCodeAt(0) - 65;

// A ROM byte in these tables is either a plain character or a token code (>=165).
function legend(b) {
  if (b >= 165) return tok(b);
  if (b === 0x7f) return '\u00a9';   // the Spectrum character set puts © at 127
  if (b === 0x60) return '\u00a3';   // ...and £ at 96, where ASCII has a backtick
  return String.fromCharCode(b);
}

// CAPS SHIFT + digit produces a control code; these are the names printed on the case.
const CTRL_NAMES = {
  0x04: 'TRUE VIDEO', 0x05: 'INV.VIDEO', 0x06: 'CAPS LOCK', 0x07: 'EDIT',
  0x08: '←', 0x09: '→', 0x0a: '↓', 0x0b: '↑',
  0x0c: 'DELETE', 0x0f: 'GRAPHICS',
};

// K-mode keyword for a letter: the ROM simply adds $A5 to the letter's code.
const kKeyword = ch => tok(ch.charCodeAt(0) + 0xa5);

// ---- Physical layout: 4 rows of 10 keys, and the keyboard matrix ----
// Each half-row is one port line; bit 0 is the key nearest the outside edge.
const MATRIX = { // key -> [half-row index 0..7, bit 0..4]
  CS:[0,0], Z:[0,1], X:[0,2], C:[0,3], V:[0,4],
  A:[1,0],  S:[1,1], D:[1,2], F:[1,3], G:[1,4],
  Q:[2,0],  W:[2,1], E:[2,2], R:[2,3], T:[2,4],
  '1':[3,0],'2':[3,1],'3':[3,2],'4':[3,3],'5':[3,4],
  '0':[4,0],'9':[4,1],'8':[4,2],'7':[4,3],'6':[4,4],
  P:[5,0],  O:[5,1], I:[5,2], U:[5,3], Y:[5,4],
  ENTER:[6,0], L:[6,1], K:[6,2], J:[6,3], H:[6,4],
  SPACE:[7,0], SS:[7,1], M:[7,2], N:[7,3], B:[7,4],
};

const ROWS = [
  ['1','2','3','4','5','6','7','8','9','0'],
  ['Q','W','E','R','T','Y','U','I','O','P'],
  ['A','S','D','F','G','H','J','K','L','ENTER'],
  ['CS','Z','X','C','V','B','N','M','SS','SPACE'],
];

// Colours printed on the digit keys (INK/PAPER numbers 0..7).
const DIGIT_COLOUR = { '0':0,'1':1,'2':2,'3':3,'4':4,'5':5,'6':6,'7':7 };

const keys = [];
for (const row of ROWS) {
  for (const id of row) {
    const k = { id, matrix: MATRIX[id] };
    if (/^[A-Z]$/.test(id)) {
      const i = letterIdx(id);
      k.main    = id;
      k.keyword = kKeyword(id);                       // white, on the key
      k.symbol  = legend(byteAt(KEY_SS, i));          // red, on the key
      k.above   = legend(byteAt(KEY_EXT, i));         // green, above the key
      k.below   = legend(byteAt(KEY_EXTSS, i));       // red, below the key
    } else if (/^[0-9]$/.test(id)) {
      const d = +id;
      k.main   = id;
      k.symbol = legend(byteAt(KEY_SS, 26)) && null;  // filled in below
      k.above  = CTRL_NAMES[byteAt(KEY_CTRL, d)];     // white, above the key
      k.below  = legend(byteAt(KEY_EXTDIG, d));       // red, below the key
      if (d in DIGIT_COLOUR) k.colour = DIGIT_COLOUR[d];
    } else {
      k.main = { CS: 'CAPS SHIFT', SS: 'SYMBOL SHIFT', ENTER: 'ENTER', SPACE: 'SPACE' }[id];
      k.special = id;
      if (id === 'SPACE') k.above = 'BREAK';
    }
    keys.push(k);
  }
}

// The only legends NOT taken from a ROM table: SYMBOL SHIFT + digit. The ROM
// derives these arithmetically inside K-DIGIT rather than storing a table, so
// they are written out here, keys 1..9 then 0.
const DIGIT_SS = '!@#$%&\'()_';
for (const k of keys) {
  if (/^[0-9]$/.test(k.id)) {
    k.symbol = k.id === '0' ? DIGIT_SS[9] : DIGIT_SS[+k.id - 1];
  }
}

// ---- Character set: 96 glyphs of 8 bytes at $3D00 (codes 32..127) ----
const font = rom.subarray(0x3d00, 0x3d00 + 96 * 8);

const out = `// GENERATED by tools/gen-data.js from the original Sinclair 48K ROM.
// Do not edit by hand - re-run the generator instead.
export const FONT_BASE64 = ${JSON.stringify(Buffer.from(font).toString('base64'))};
export const TOKENS = ${JSON.stringify(tokens)};
export const KEYS = ${JSON.stringify(keys, null, 1)};
`;
fs.writeFileSync(path.join(ROOT, 'js', 'rom-data.js'), out);
console.log('wrote js/rom-data.js:', keys.length, 'keys,', Object.keys(tokens).length, 'tokens, font', font.length, 'bytes');
